FROM nginx:alpine as main

COPY --from=build /app/site-min.js front/assets/dist/js/.
COPY --from=build /app/firebase-min.js front/assets/dist/js/.

COPY front /usr/share/nginx/html
COPY front-nginx.conf /etc/nginx/conf.d/default.conf
