version: "3.8"

services:

  rigapp_fe:
    image: ${DOCKER_IMAGE_FE}
    container_name: ${CONTAINER_NAME_FE}
    networks:
      - nginxproxymanager_default
    ports:
      - "9090:80"

  rigapp_be:
    image: ${DOCKER_IMAGE_BE}
    container_name: ${CONTAINER_NAME_BE}
    restart: always
    depends_on:
      - rigapp_database
    networks:
      - rigapp
      - nginxproxymanager_default
    ports:
      - "5000:5000"
    
  rigapp_database:
    image: postgres:14.5-alpine3.16
    container_name: rigapp-postgres
    volumes:
      - "rigapp_pg_data:/var/lib/postgresql/data"
    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - rigapp
    ports:
      - "5432:5432"

volumes:
  rigapp_pg_data:

networks:
  rigapp:
    external: true
  nginxproxymanager_default:
    external: true
