version: "3.8"

services:

  rigapp_fe:
    image: rigapp-fe:latest
    container_name: rigapp-fe
    networks:
      - qualitygate
    ports:
      - "8080:80"

  rigapp_be:
    image: rigapp-be:latest
    container_name: rigapp-be
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - qualitygate
    ports:
      - "5001:5000"
    
  rigapp_database:
    image: postgres:14.5-alpine3.16
    container_name: rigapp-postgres
    volumes:
      - "rigapp_pg_data:/var/lib/postgresql/data"
    environment:
        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - qualitygate
    ports:
      - 5432

volumes:
  rigapp_pg_data:

networks:
  qualitygate:
    external: true