
@Library('MyJenkins@main')
import br.com.twocode.Commands
import br.com.twocode.ProjectMetadata

def projectMetadata = new ProjectMetadata();
def cmd = new Commands();

projectMetadata.projectName = "randomwebimages"
projectMetadata.dockerfile = "Dockerfile"
projectMetadata.language = "randomwebimages"
projectMetadata.version = "1.0"
projectMetadata.sourcesPath = "src"

cmd.exec(projectMetadata);
